version: '1.0'
services:
     mongodb:
        container_name: BlazorWithMongoDB
        image: mongo
        ports:
            - 27017:27017
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        volumes: 
            - mongo-data
     mongo-express:
        container_name: BlazorWithMongoExpress
        image: mongo-express
        ports:
            - 8081:8081
        environment: 
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
            - ME_CONFIG_MONGODB_SERVER=BlazorWithMongoDB
     blazor-mongo-website:
         container_name: BlazorWithMongoWebsite
         image: blazor-mongo-website
         ports:
             - 8080:8080
         environment:
             - BlazorDatabase__ConnectionString=mongodb://admin:admin@localhost:27017
             - BlazorDatabase__DatabaseName=blazorDB
             - BlazorDatabase__BooksCollectionName=Books
     volumes:
         mongo-data:
           driver: local
     